services:
  app:
    container_name: go-auth-globo
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ISSUER: ${ISSUER}
      REDIS_URL: ${REDIS_URL}
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_SECRET: ${REDIS_SECRET}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}

    depends_on:
      - redis
      - postgres
    networks:
      - mynet

  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - mynet

  postgres:
    image: postgres
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - mynet

networks:
  mynet:
    driver: bridge