CREATE TABLE users (
    id INTEGER PRIMARY KEY NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(140) NOT NULL,
    email VARCHAR(100) NOT NULL,
    senha VARCHAR(255) NOT NULL
);

-- a senha é teste@123
INSERT INTO users (nome, email, senha) values ('Rodrigo', 'rodrigo@gmail.com', '$2a$10$tWWAkdjWmId2JyUsHB69qeGS0WJ0yyoNsX9RHvheNUaM.yHIXY/pS');